---
title: "Metadata format: detailed"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Metadata format: detailed}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

some [text]{style="background-color: blue"}

## Design principles

`epicdata` wants to be a user-friendly, yet comprehensive data processing and cleaning tool for all types of epidemiological studies. We therefore adhere to the following design principles:

-   Modular workflow: `epicdata` follows a data processing workflow (see [here]{style="background-color: blue"} for details) but you can choose, which workflow modules you need.
-   Metadata as only input: `epicdata` creates your processing code from the metadata alone. Your individual workflow is concluded from your metadata. If you, e.g., don't specify any contradictions, `epicdata` will skip contradiction checks.
-   Modular metadata: You only specify what you need. If you have no date variables, there's no need to specify a date format.
-   Forgiving: Whenever possible, metadata can be specified in different ways to remove barriers in metadata creation. Did you forget if you need to specify date.format or format.date? No problem, `epicdata` understands both.
-   Complete logging: Data cleaning will lead to changes in individual data values. `epicdata` logs every single change that is made throughout the cleaning process.
-   Automate as much as possible: The user only needs to provide metadata and decide what to do with problematic data values. `epicdata` creates the code, applies your decisions, and creates a data dictionary.
-   Interactive: Even though `epicdata` automates as much as possible, it is still run interactively, i.e., while the user is on the other side of the keyboard. During the process, the user needs to confirm the results of different workflow steps. If you are looking for a automated data validation process, try packages `pointblank` or `dataquieR`.
-   Usable for non-veteran R users: Metadata is specified in human readable YAML format. `epicdata` creates R code. User decisions can be inputted in user-friendly ways.
-   Separate data manager and expert roles: There are often situations in which the data manager is not making decisions on how to proceed with problematic values. `epicdata` therefore provides a mode, in which decision-making can be separated from data cleaning. Decision-makers are not assumed to be R users.

## Format (YAML)

In `epicdata`, metadata is specified in **YAML** format. YAML has been designed to be readable for both humans and computers. This is accomplished by **indentations**, i.e., the distance a line of text is moved towards the right. The indentation thereby defines a hierarchy of the individual elements. In other formats, such a hierarchy needs additional text elements, which hurts human readability. This means, however, that errors in indentations will lead to misspecification of metadata information. (Usually, the next layer is 2 spaces or a tab towards the right. RStudio provides an "indentation guide" that visually highlights the indentation. To activate it, go to Tools/Global Options/Code/Display. If nothing changes, adjust your theme in Tools/Global Options/Appearance.)

``` yaml
First.layer
  Second.layer
  Second.layer
    Third.layer
  Second.layer
First.layer
  Second.layer
```

Colons `:` are used to specify **key-value pairs**, i.e., an element of a certain name (key) as well as its corresponding value. Per line, only one key-value pair is specified. The basic syntax is `key: value`. **Always include a space after the colon.** Usually no quotation marks `""` are necessary when specifying values. Some exceptions are listed below. Almost all keys are pre-defined by `epicdata` to structure your metadata. The values usually must have a specific format, e.g. a number, or come from a list of allowed values. The values `yes` and `no` (similarly to `true` and `false`) will be transformed to `TRUE` and `FALSE` in R.

When to use quotation marks `""`:

-   By default, you don't need to wrap strings in quotation marks
-   Use them, however, if you start a value with a special symbol (non-letter and non-number) apart from dot `.` and underscore `_`
-   Use them, however, if the string is only a dot `"."`
-   Use them as well, if you want to force a value to be a string. The `calling.code` in the example below would be read as the positive number `33` without quotation marks.
-   The same rules apply to keys and values, i.e., the part in front and after the colon `"key": "value"`
-   If reading your metadata leads to a `Loading YAML metadata failed!` error with the line number of the problem's location, try wrapping it in quotation marks as your first debugging activity.

``` yaml
name: France
capital: Paris
population.million: 68
eu.member: yes
calling.code: "+33"
```

Instead of individual key-value pairs, you can also map other objects to a key, e.g., several key-value pairs. This is achieved by using indentations. In the example below, the key-value pairs of `capital`, `population.million`, `eu.member`, and `calling.code` are mapped to the corresponding country. Notice that no values appear in the same line as the keys `France` and `Germany`, because the indented key-value pairs are mapped to it. In addition, `France` and `Germany` with their key-value pairs are mapped to `countries`.

``` yaml
countries:
  France:
    capital: Paris
    population.million: 68
    eu.member: yes
    calling.code: "+33"
  Germany:
    capital: Berlin
    population.million: 84
    eu.member: yes
    calling.code: "+49"
```

Dashes `-` are used to form **lists**. Even though the YAML language can be more complicated, we only use dashes for lists of values when you need to map multiple values to the same key. All values in the same list need to have the same indentation and all of them have a dash. For this, the two space indentation is replaced by one dash and one space (`- value`). In the example below, since France only has one city with more than one million inhabitants, the value is specified as an ordinary key-value pair. However, since Germany has four cities with more than one million inhabitants, we need to specify a list. Notice that the dash has the same indentation as `million.cities`, but due to the dash and the additional space, the values themselves (`Berlin`, `Hamburg`, etc.) are indented by two characters, as usual.

``` yaml
countries:
  France:
    capital: Paris
    population.million: 68
    eu.member: yes
    calling.code: "+33"
    million.cities: Paris
  Germany:
    capital: Berlin
    population.million: 84
    eu.member: yes
    calling.code: "+49"
    million.cities:
    - Berlin
    - Hamburg
    - Munich
    - Cologne
```

YAML code is not specified in R files but in special text files with file extension `.yml`. The `yml` files can be created by function `xx()` and edited in R Studio. Therefore, the use of R Studio is recommended. See `xx` for more information on how to create your metadata.

## Metadata design principles

-   Including a key without specifying a value is equal to not including the key at all.

``` yaml
options:
  data.name: epicdata
  id.var:
  load.from: folder
```

is equal to

``` yaml
options:
  data.name: epicdata
  load.from: folder
```

-   Not specifying a key contains information for some keys as it defaults to a pre-specified value. (See the end of this vignette for a complete list of defaults.)

-   Whenever useful, different spellings are offered, e.g., `date.format` and `format.date`.

## Components

In `epicdata`, metadata consists of several components:

-   `options`: A list of options specifying study information, e.g. `data.name`, selecting workflow modules, e.g. `double.entry`, and defining global variable defaults, e.g. `date.format`.
-   `var.list`: A list of all variables, where variable-specific information is provided.
-   `var.groups`: A list of variable groups with information that applies to the group instead of individual variables.
-   `na.codes`: A list of codes that will represent missing values in the processed data set.
-   `contras`: A list of implausible combinations of values from two variables.

The components form the first layer of the metadata hierarchy. They are the only values specified in the first layer. Specify them with a colon and without any dashes. The components can be specified in any order. If you are not adding any values below a certain component, you can leave it out completely.

``` yaml
options:
  tbd
var.list:
  tbd
var.groups:
  tbd
na.codes:
  tbd
contras:
  tbd
```

## Component: options

Options are key-value pairs below component `options`. List all key-value pairs on the second layer without any dashes. In the list of option keys below, allowed values for the corresponding key are found in the brackets after each key.

**Study information**

-   `data.name` (Text): A short name for your dataset that is used for project and file names. If missing, a generic name will be used instead.

-   `id.var` (Name of variable specified in `var.list`): The name of the ID variable, which is used to identify observations. Allowed are the variable names specified in `var.list` as `id`. Duplicate values in the ID variable are allowed only if `double.entry: yes`. If missing, a generic ID variable will be added temporarily. Mandatory when `double.entry: yes` or `id.pattern` has been specified.

-   `id.pattern` (Regular expression): A regex pattern that must be fulfilled for all values of the variable specified in `id.var`. Rows with non-matching IDs are excluded. **Wrap the value in quotation marks**, e.g., `"[:digit:]{5}"`!

**Workflow module selection**

-   `id.list` (boolean, i.e., `true`, `yes`, `false`, `no`): Indicate if a list with valid IDs is provided. An `id.list` makes sense if users are unsure how to specify an `id.pattern` with regular expressions, if the `id.pattern` is not sufficient to differentiate between valid and invalid IDs, i.e., some IDs with the specified pattern are valid and some are not, or if a list of all used IDs is easily available. Should not (Cannot??) be combined with `id.pattern`.

-   `consent` (boolean, i.e., `true`, `yes`, `false`, `no`): Indicate if informed consent will be checked. Can only be `true`, if an `id.var` has been specified.

-   `load.from` (one of: `folder`, `db`): Defines which code module for reading raw data is used. If `folder`, data is read from the `Input` folder in the project. If `db`, data is read from a database. If missing, defaults to `folder`.

-   `double.entry` (boolean, i.e., `true`, `yes`, `false`, `no`): Non-digital data has been entered multple times (usually twice) to avoid errors during data entry. This option activates sub-module DUP_COMPARE.

-   `remove.vars` (boolean, i.e., `true`, `yes`, `false`, `no`): If `yes`, variables in the data that are missing from the metadata are removed from the data.

**Global variable defaults**

-   `yesno` (value like `cats`): Specify categories for Yes/No-questions, which can be re-used in `var.list`.

-   `yesno.eng` (value like `cats.eng`): If in `var.list`, `cats` is set to `yesno`, this value is automatically used for `cats.eng`.

-   `date.format` or `format.date` (one of: `ymd`, `ydm`, `mdy`, `myd`, `dmy`, `dym`): Defines the default date format. The value specified here is used for all variables of `type: date` for which no individual `format` is defined in `var.list`. If all date variables have a format defined, `date.format` has no impact. In `epicdata`, `lubridate` functions are used to process dates. The possible values define the order of day (d), month (m) and year (y). See `lubridate::ymd()` for possible date formats that can be processed with these functions. Mandatory when there are variables of `type: date` and not all of them have key `format` defined in `var.list`. Do not use both `date.format` and `format.date`.

-   `time.format` or `format.time` (one of: `hms`, `hm`, `ms`):

-   `datetime.format` or `format.datetime` (one of: ):

-   `to.na` (Text):

-   `touch.na` (boolean, i.e., `true`, `yes`, `false`, `no`):

-   `to.factor` (boolean, i.e., `true`, `yes`, `false`, `no`):

``` yaml
options:
  data.name: epicdata
  id.var: id
  id.pattern: "[:digit:]{5}"
  date.format: dmy
```

+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| Option            | Alternative names | Length      | Do not specify together with ... | Only specify together with ... |
+===================+===================+=============+==================================+================================+
| `data.name`       |                   | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `id.var`          |                   | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `id.pattern`      |                   | 1           | `id.list`                        | `id.var`                       |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `id.list`         |                   | 1           | `id.pattern`                     |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `consent`         |                   | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `load.from`       |                   | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `double.entry`    |                   | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `remove.vars`     | `vars.remove`     | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
|                   |                   |             |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `date.format`     | `format.date`     | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `time.format`     | `format.time`     | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `datetime.format` | `format.datetime` | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `to.na`           | `na.to`           | \>=1        |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `touch.na`        | `na.touch`        | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+
| `to.factor`       |                   | 1           |                                  |                                |
+-------------------+-------------------+-------------+----------------------------------+--------------------------------+

## Component: var.list

The list of variables `var.list` is the core of the metadata and a mandatory part of it. The second layer contains the variable names. The third layer contains key-value pairs that provide information regarding the corresponding variable. The same keys are re-used for each variable.

``` yaml
var.list:
  var1:
    key: value
    ...
  var2:
    key: value
    ...
```

Note that, in the example above, `var1` and `var2` are the variable names and that there is no value after the colon `:` in their lines. Variable names must be syntactically valid names (see `?make.names` for details). The key-value pairs below `var1` describe the characteristics of `var1`, while the key-value pairs below `var2` describe characteristics of `var2`. Many keys only apply to certain variable types. Do not specify keys that apply to other types of variables. The list below is structured by the type of variable the keys apply to.

**Keys that apply to all variables:**

-   `type` (one of: `text`, `cat`, `num`, `date`, `time`, `datetime`): The variable `type` is the main variable characteristic and the only key that is **always** **required**. There are 6 different types:

    -   `text`: This type is for variables that holds text or IDs.
    -   `cat`: This type is for categorical variables. Categorical variables have integer codes that each refer to one category, e.g., `0` refers to `no` and `1` refers to `yes`. By default, the variables are of type `integer` in the final data set with the category descriptions, i.e., labels, described in the data dictionary. However, you can choose to transform them to `factor`.
    -   `num`: This type is for numeric variables, i.e., variables that you define as numbers. Likert scale variables or their sum score, e.g., might be defined as type `cat` or `num`.
    -   `date`: This type is for variables that are dates without a time component, e.g., birthdays. They consist of day, month, and year, but you can select specific formats (see below).
    -   `time`: This type is for variables that describe a time of day without a date or a duration in hours, minutes, and/or seconds. There are three versions: hours and minutes, minutes and seconds, hours and minutes and seconds.
    -   `datetime`: This type is for variables that have both a date and a time component as described above.

-   `old.id` or `id.old` (a syntactically valid name, see `?make.names` for details): If you want to change the name of a variable, put the old name in `old.id` and use the new name as the variables name. Cannot be used together with `new`. See also section "Variable names in the data set" below.

-   `label` (Text): A description of the variable. `label` is not mandatory but highly recommended. Each variable should have a `label`. If your variable comes from a questionnaire, use the question as the label. If your questionnaire is not in English, use the original version and specify an English translation in key `label.eng`.

-   `label.eng` (Text): If the `label` is not in English, enter its English translation here for use in the data dictionary. `label.eng` can only be used if `label` is specified as well.

-   `to.na` or `na.to` (text):

-   `touch.na` or `na.touch` (boolean, i.e., `true`, `yes`, `false`, `no`): If `no`, all `NA`s, after applying `to.na`, will remain as `NA`. If `yes`, `NA`s are processed as usual. Defaults to the global option `touch.na`, or, if the global options has not been specified, to `yes`.

-   `na.else` (a missing code): The missing code (as defined in component `na.codes`) specified here is used to replace `NA`s if no rule in `na.rules` applies. Must be specified always, apart from situations when the variable has no `NA`s or when `touch.na` is set to `no`.

-   `na.rules` ():

-   `na.switch` ():

-   `na.keep` ():

-   `na.replace` ():

-   `group` (a syntactically valid name, see `?make.names` for details): The name of the variable group, to which the variable belongs. Each variable can only belong to one variable group, but it doesn't have to. All variables with the same value for key `group`, i.e., group name, belong to the same group. Use the group name in component `var.groups` to specify group-specific attributes and defaults, and to trigger documentation of the group together instead of each variable separately.

``` yaml
var.list:
  sport_1:
    type: cat
    label: Football
    group: sport
  sport_2:
    type: cat
    labe: Swimming
    group: sport
var.groups:
  sport:
    group.label: What's your favourite sport?
```

-   `sub` (): Use `sub`, when the variable is a sub-variable of one other variable, e.g., "Did you x?" - "If yes, y".
-   `new` (): Create new variables based on existing variables by specifying `new`. If `new` is specified, its name must not be in the data set. Also, `old.id` cannot be used. New variables are created with `dplyr::mutate()`, where the variable definition is specified as a name-value pair using tidy evaluation with data masking. For `new`, specify the value of this name-value pair. As an example, variable `mass_norm` would be created by `data.frame %>% mutate(mass_norm = mass / mean(mass, na.rm = TRUE))`. To recreate the creation of `mass_norm` in `epicdata`, `mass` must be a variable specified in `var.list`, `mass_norm` is the name for your new variable, while `mass / mean(mass, na.rm = TRUE)` is specified for `new`. If your value causes an error, try to wrap it in quotation marks.

``` yaml
var.list:
  mass:
    ...
  mass_norm:
    ...
    new: mass / mean(mass, na.rm = TRUE)
```

-   `changes` ():

**Text variables:**

-   `ops` (a variable or group name): add separation of one variable that contains both the checkbox value and the free text, as in modern limesurvey
-   `dict` ():
-   `dict.rules` ():

**Categorical (cat) variables:**

-   `cats` ():

``` yaml
var.list:
  var1:
    type: cat
    cats:
    - 0 = no
    - 1 = yes
```

You don't need to remember if the integer or the label goes first, as `epicdata` understands both. You can even mix them up. It can also handle different amounts of white space between the components. Just make sure you include a single space after the dash in the front.

``` yaml
var.list:
  var1:
    type: cat
    cats:
    - no=0
    - 1 =yes
    - maybe      =   2
```

-   `cats.eng` ():

``` yaml
var.list:
  var1:
    type: cat
    cats:
    - 0 = nein
    - 1 = ja
    cats.eng:
    - 0 = no
    - 1 = yes
```

-   `cats.rules` ():

-   `to.factor` (boolean, i.e., `true`, `yes`, `false`, `no`): If `yes`, transforms the variable to factor.

-   `factor.name` or `name.factor` (): If `to.factor` is `yes` or not specified, a new variable is created and turned to factor while this variable stays integer. Provide the name of the new factor variable.

**Numeric (num) variables:**

-   `from` ():

-   `from.exclude` ():

-   `to` ():

-   `to.exclude` ():

-   `limit.rules` ():

**Date variables:**

-   `format` or `date.format` or `format.date` ():

-   `from` ():

-   `from.exclude` ():

-   `to` ():

-   `to.exclude` ():

-   `limit.rules` ():

**Time variables:**

-   `format` or `time.format` or `format.time` ():

-   `from` ():

-   `from.exclude` ():

-   `to` ():

-   `to.exclude` ():

-   `limit.rules` ():

**Datetime variables:**

-   `format` or `datetime.format` or `format.datetime` ():

-   `from` ():

-   `from.exclude` ():

-   `to` ():

-   `to.exclude` ():

-   `limit.rules` ():

**Variable names in the data set:**

The data set must contain a certain set of variables based on the metadata specification:

-   In general, all variable names (the values on the second layer, i.e., `var1`, `var2`, `var3`, `var4`, `var5`) have to be variables in the data set. There are, however, exceptions.
-   If `old.id` has been specified, the variable name must **not** be in the data set. Instead, the value specified for `old.id` has to.
-   If `new` has been specified, the variable name must **not** be in the data set. You cannot specify `new` and `old.id` for the same variable.
-   If you specify `factor.name` or `group`, the corresponding values must **not** be variables in the data set.

In the example below, the data set, therefore, must contain exactly the following variables: `var1`, `VAR_TWO`, `var4`. (`var5` and `VAR_FIVE` are invalid. If you would want to use this metadata, you would need to delete `var5` first, as it would cause an error.)

``` yaml
# in dataset?
var.list:
  var1: # yes
    type: num
  var2: # no
    type: text
    old.id: VAR_TWO # yes
  var3: # no
    type: num
    new: log(var1)
  var4: # yes
    type: cat
    factor.name: var4_factor # no
    group: set1 # no
  var5: # invalid (cannot mix old.id and new)
    type: num
    old.id: VAR_FIVE
    new: 2 * var1
```

**Summary of variable keys:**

+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| Key               | Alternative names                                     | Length                                                                               | Do not specify together with ... | Only specify together with ...                   |
+===================+=======================================================+======================================================================================+==================================+==================================================+
| `type`            |                                                       | 1 (required)                                                                         |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `old.id`          | `id.old`                                              | 1                                                                                    | `new`                            |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `label`           |                                                       | 1                                                                                    |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `label.eng`       | `eng.label`                                           | 1                                                                                    |                                  | `label`                                          |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `na.else`         | `else.na`                                             | 1                                                                                    |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `na.rules`        | `rules.na`                                            | \>=1                                                                                 |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `na.switch`       | `switch.na`                                           | \>=1                                                                                 |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `na.keep`         | `keep.na`                                             | \>=1                                                                                 |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `na.replace`      | `replace.na`                                          | \>=1                                                                                 |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `to.na`           | `na.to`                                               | \>=1                                                                                 |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `touch.na`        | `na.touch`                                            | 1                                                                                    |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `group`           |                                                       | 1                                                                                    |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `sub`             |                                                       | 1                                                                                    |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `new`             |                                                       | 1                                                                                    | `old.id`                         |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `changes`         |                                                       | \>=1                                                                                 |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `ops`             |                                                       | 1                                                                                    |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `dict`            |                                                       | \>1                                                                                  |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `dict.rules`      | `rules.dict`                                          | \>=1                                                                                 |                                  | `dict`                                           |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `cats`            |                                                       | \>1 (required if type `cat`, but might be specified in `var.groups`)                 |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `cats.eng`        | `eng.cats`                                            | \>1                                                                                  |                                  | `cats`                                           |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `cats.rules`      | `rules.cats`                                          | \>=1                                                                                 |                                  | `cats`                                           |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `to.factor`       |                                                       | 1                                                                                    |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `factor.name`     | `name.factor`                                         | 1                                                                                    |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `from`            |                                                       | 1                                                                                    | `from.exclude`                   |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `from.exclude`    | `from.ex`                                             | 1                                                                                    | `from`                           |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `to`              |                                                       | 1                                                                                    | `to.exclude`                     |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `to.exclude`      | `to.ex`                                               | 1                                                                                    | `to`                             |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `limit.rules`     | `rules.limit`, `limits.rules`, `rules.limits`         | \>=1                                                                                 |                                  | `from` OR `from.exclude` OR `to` OR `to.exclude` |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `date.format`     | `format.date`, `format` (if `type` is `date`)         | 1 (required if type `date`, but might be specified in `var.groups` or `options`)     |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `time.format`     | `format.time`, `format` (if `type` is `time`)         | 1 (required if type `time`, but might be specified in `var.groups` or `options`)     |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+
| `datetime.format` | `format.datetime`, `format` (if `type` is `datetime`) | 1 (required if type `datetime`, but might be specified in `var.groups` or `options`) |                                  |                                                  |
+-------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------------+--------------------------------------------------+

## Component: na.codes

In the final processed data sets, NAs are usually replaced by missing codes. These codes represent a certain type or reason of missingness. In the component `na.codes`, certain values are declared as missing codes in order to allow `epicdata` to treat them appropriately, e.g., by including them in the data dictionary. In `na.codes`, no reference to certain variables is made yet. Here, only the declaration is done.

Every missing code is declared as one key-value pair with the code being the key and the description being the value.

``` yaml
na.codes:
  9001: Not answered
  9002: Not enough blood for analysis
  8001: Skipped because question is not applicable
  9001-01-01: Not answered (date)
  90h01m00s: Not answered (time hms)
```

The missing codes used in the final data set must be of the same type (text, cat, num, date, datetime, time) as the variable. We therefore recommend to use integers, as they can be used in the same form for variables of type text, cat, and num. When an integer is used for date, datetime, or time, it is automatically transformed by the following rules:

**Single digit, e.g.,** `9`**:**

-   `date`: Add value in years to the date 9000-01-01, e.g., `9009-01-01`
-   `datetime`: Add value in years to the datetime 9000-01-01 00:00:00, e.g., `9009-01-01 00:00:00`
-   `time` (format: `hms`): Use the value in every digit, e.g., `99:99:99`, `99h99m99s`
-   `time` (format: `hm`): Use the value in every digit, e.g., `99:99`, `99h99m`
-   `time` (format: `ms`): Use the value in every digit, e.g., `99:99`, `99m99s`

**Two digits, e.g.,** `99`**:**

-   `date`: Add value in years to the date 9000-01-01, e.g., `9099-01-01`
-   `datetime`: Add value in years to the datetime 9000-01-01 00:00:00, e.g., `9099-01-01 00:00:00`
-   `time` (format: `hms`): Use the value for hours, minutes, and seconds, e.g., `99:99:99`, `99h99m99s`
-   `time` (format: `hm`): Use the value for hours and minutes, e.g., `99:99`, `99h99m`
-   `time` (format: `ms`): Use the value for minutes, and seconds, e.g., `99:99`, `99m99s`

**Three digits, e.g.,** `101`**:**

-   `date`: Add value in years to the date 9000-01-01, e.g., `9101-01-01`
-   `datetime`: Add value in years to the datetime 9000-01-01 00:00:00, e.g., `9101-01-01 00:00:00`
-   `time` (format: `hms`): Add the first digit in hours and the last two digits in minutes to the time 90:00:00, e.g., `91:01:00`, `91h01m00s`
-   `time` (format: `hm`): Add the first digit in hours and the last two digits in minutes to the time 90:00, e.g., `91:01`, `91h01m`
-   `time` (format: `ms`): Add the first digit in minutes and the last two digits in seconds to the time 90:00, e.g., `91:01`, `91m01s`

**Four digits, e.g.,** `9001`**:**

-   `date`: Use the value as the year of the date xxxx-01-01, e.g., `9001-01-01`
-   `datetime`: Use the value as the year of the datetime xxxx-01-01 00:00:00, e.g., `9001-01-01 00:00:00`
-   `time` (format: `hms`): Use the value for hours and minutes, e.g., `90:01:00`, `90h01m00s`
-   `time` (format: `hm`): Use the value for hours and minutes, e.g., `90:01`, `90h01m`
-   `time` (format: `ms`): Use the value for minutes, and seconds, e.g., `90:01`, `90m01s`

If the automatic transformation does not provide values that make sense for missing codes (values that cannot be confused with real values), you can provide date, datetime, and time values for missing codes as well. The values you choose must be in the same format as the corresponding variable, e.g., `9001-01-01` for format `ymd` and `01.01.9001` for format `dmy`. For time formats, we recommend using the letters `h` (for hours), `m` (for minutes), and `s` (for seconds) after the corresponding number, e.g., `90h01m00s`, `90h01m`, `01m00s`.

## Components: contras

## Components: var.groups

Often, variables in the same group are of the same type, e.g., `cat`, but they don't have to be. The specified defaults for type-specific keys of course only apply the variables of the corresponding type.

In the data dictionary, the variables appear in the same order as in the YAML input. Analogously, within a variable group,

In single-choice questions, questionnaire participants select one of the given options. In multiple-choice (mc) questions, they can select multiple options. While single-choice questions can be fit into a single categorical (type `cat`) variable with one category per option, multiple-choice questions need one variable per option. The multiple-choice questions are usually binary, i.e., type `cat` with two categories indicating selection and non-selection. In component `var.list`, you can indicate with key `mc.set` that the corresponding variable belongs to a multiple-choice set, i.e., is one of the multiple variables necessary to describe a multiple-choice question. Specifying the same value in `mc.set` tells `epicdata` that the variables belong to the same multiple-choice question.

In component `var.groups`, additional information can be provided for the set. Use the following keys:

-   `group.label` (Text): Define a `label` for the mc.set. If a `label` is specified, the variables that belong to the set are documented together. We recommend to put the question in `label` in `mc.sets` and specify the option that each variable represents in `label` in `var.list`.

-   `group.label.eng` (Text): Similar to `var.list`, specify here the English translation of the value in `label`, if it is not in English already. The English version can be used to create an English data dictionary.

-   `mc.exclusive` (boolean, i.e., `true`, `yes`, `false`, `no`): If the variable is part of a multiple choice (mc) set, it can be defined as an exclusive answer. A common example is a multiple choice set with option "none of the other options". It is implausible that "none of the other options" and another option are both selected. Setting `mc.exclusive` to `yes` automatically includes the corresponding contradictions. Contradictions are only included if the mc variables have only categories `0` and `1` while `1` is assumed to indicate selection of the corresponding option. If the exclusive variable is called `var_exclusive` and another variable in the same mc set is called `var_mc1`, then the following contradiction is added: `var_exclusive == 1 & var_mc1 == 1`. This type of contradiction is added for all other mc variables in the set. Only specify `mc.exclusive`, if you also specified `mc.set`.

-   `cats` (): To shorten the specification of the multiple-choice variables in `var.list`, their categories can be specified in `mc.sets` and are applied to all variables in the set.

-   `cats.eng` (): Similar to `var.list`, specify the English translations of the categories here to create an English version of the data dictionary, if the questionnaire is not in English already.

-   `to.factor` (boolean, i.e., `true`, `yes`, `false`, `no`): Sets the default for all variables in the set to the specified value. Therefore, if `yes` is specified, `to.factor` of all variables in the mc.set is set to `yes` as well. You can overwrite the value for individual variables by setting their value in `var.list` back to `no`.

``` yaml
var.list:
  sport1:
    type: cat # always specify the variable type
    label: football # only put in the option, the question is specified below
    group: sport # all variables with value "sport" belong together
  sport2:
    type: cat
    label: swimming
    group: sport
  sport3:
    type: cat
    label: running
    group: sport
  sport4:
    type: cat
    label: none
    group: sport
  sport_where1:
    type: cat
    label: gym
    group: sport_where
    cats:
    - 0 = no
    - 1 = yes
  sport_where2:
    type: cat
    label: outside
    group: sport_where
    cats: # specifying the categories in every variable is equal to specifying it in var.groups
    - 0 = no
    - 1 = yes
var.groups:
  sport:
    group.label: What's your favourite sport? # specify the question for variables sport1-4
    cats: # specify the categories for variables sport1-4
    - 0 = no
    - 1 = yes
    mc.exclusive: sport4 #if sport4 is selected no other variable in the group should
  sport_where:
    group.label: Where do you exercise?
```

## Defaults

In `epicdata`, not specifying a value also holds information. This is accomplished by default values. `epicdata` selects values by going through a following **cascade of defaults**:

1.  Use value specified in `var.list`
2.  If 1. is `NULL`, i.e., not specified, use value specified in `var.groups`
3.  If 2. is `NULL`, i.e., not specified, use value specified in `options`
4.  If 3. is `NULL`, i.e., not specified, use the pre-defined default
5.  If 4. is `NULL`, the final value is `NULL`

For group-specific keys, i.e., keys that do not appear in `var.list` but only in `var.groups`, step 1 is, of course, skipped. For options, i.e., keys that do not appear in `var.list` and `var.groups`, steps 1 & 2 are, of course, skipped.

**Pre-defined defaults** are default values specified in `epicdata` itself. Some pre-defined defaults are different based on a certain condition.

+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| var.list                                                               | var.groups        | options           | pre-defined                                                                                     |
+========================================================================+===================+===================+=================================================================================================+
| \-                                                                     | \-                | `data.name`       | `my_data`                                                                                       |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | \-                | `id.var`          | Adds a variable called `.id.var`, which contains numbers from 1 to N. It is deleted in the end. |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | \-                | `id.pattern`      | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | \-                | `id.list`         | `FALSE`                                                                                         |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | \-                | `load.from`       | `folder`                                                                                        |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | \-                | `consent`         | IF `id.var` has been specified: `TRUE`; ELSE: `FALSE`                                           |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | \-                | `double.entry`    | `FALSE`                                                                                         |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | \-                | `remove.vars`     | `FALSE`                                                                                         |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | `group.label`     | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | `group.label.eng` | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| \-                                                                     | `mc.exclusive`    | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `type`                                                                 | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `old.id`                                                               | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `label`                                                                | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `label.eng`                                                            | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `na.else`                                                              | `na.else`         | `na.else`         | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `na.rules`                                                             | `na.rules`        | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `na.switch`                                                            | `na.switch`       | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `na.keep`                                                              | `na.keep`         | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `na.replace`                                                           | `na.replace`      | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `to.na`                                                                | `to.na`           | `to.na`           | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `touch.na`                                                             | `touch.na`        | `touch.na`        | `TRUE`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `group`                                                                | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `new`                                                                  | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `changes`                                                              | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `ops`                                                                  | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `dict`                                                                 | `dict`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `dict.rules`                                                           | `dict.rules`      | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `cats`                                                                 | `cats`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `cats.eng`                                                             | `cats.eng`        | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `cats.rules`                                                           | `cats.rules`      | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| IF `to.factor` is `NULL` and `factor.name` has been specified: `TRUE`\ | `to.factor`       | `to.factor`       | `FALSE`                                                                                         |
| ELSE: `to.factor`                                                      |                   |                   |                                                                                                 |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `factor.name`                                                          | `NULL`            | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `from`                                                                 | `from`            | `NULL`            | `-Inf`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `from.exclude`                                                         | `from.exclude`    | `NULL`            | `-Inf`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `to`                                                                   | `to`              | `NULL`            | `Inf`                                                                                           |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `to.exclude`                                                           | `to.exclude`      | `NULL`            | `Inf`                                                                                           |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `limit.rules`                                                          | `limit.rules`     | `NULL`            | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `date.format`                                                          | `date.format`     | `date.format`     | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `time.format`                                                          | `time.format`     | `time.format`     | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+
| `datetime.format`                                                      | `datetime.format` | `datetime.format` | `NULL`                                                                                          |
+------------------------------------------------------------------------+-------------------+-------------------+-------------------------------------------------------------------------------------------------+

For keys that can be **lists**, i.e., can contain 2 or more values, the default is replaced completely with the specified value. Default and specified value are **not** combined. Otherwise, it would not be possible to de-select default values. In the example below, variable key `example` can be a list and it's default `example.dafault` has been set to `A, B`. Variable `var1` overwrites the default and its final value for `example` is only `C`; it's not the combination of default and value `A, B, C`. For variable `var2`, `example` has not been specified, so the default value is used instead, i.e., `A, B`. For variable `var3`, we actually want to include the values specified as the default. Therefore, we need to include them in the list when specifying the value. To summarize, the values of key `example` for all three variables are: `var1`: `C`; `var2`: `A, B`; `var3`: `A, B, C`.

``` yaml
options:
  example.dafault:
  - A
  - B
var.list:
  var1:
    type: text
    example: C
  var2:
    type: text
  var3:
    type: text
    example:
    - A
    - B
    - C
```
